--[[
    UnitDefs.lua
    All unit type definitions for War of Jonk
    Matches the browser version's UNIT_DEFS exactly
]]

local UnitDefs = {}

UnitDefs.Types = {
    king = {
        name = "King",
        icon = "crown",       -- Roblox-friendly icon name
        emoji = "\u{265A}",   -- for UI display
        theatre = "infantry",
        hp = 100,
        maxHp = 100,
        atk = 25,
        def = 20,
        move = 1,
        range = 1,
        cost = 0,
        deployable = false,
        unique = true,
        ability = "Aura of Command",
        abilityDesc = "When King takes damage, all friendly troops lose 10% HP. Killing the King ends the game.",
    },
    guard = {
        name = "Guard Jonk",
        icon = "shield",
        emoji = "\u{1F6E1}",
        theatre = "infantry",
        hp = 80,
        maxHp = 80,
        atk = 18,
        def = 30,
        move = 1,
        range = 1,
        cost = 20,
        deployable = true,
        ability = "Royal Shield",
        abilityDesc = "Intercepts any attack targeting the King within 1 tile.",
    },
    spear = {
        name = "Spear Jonk",
        icon = "sword",
        emoji = "\u{1F5E1}",
        theatre = "infantry",
        hp = 60,
        maxHp = 60,
        atk = 22,
        def = 12,
        move = 2,
        range = 1,
        cost = 15,
        deployable = true,
        ability = nil,
        abilityDesc = "Standard aggressive infantry.",
    },
    marine = {
        name = "Marine Jonk",
        icon = "gun",
        emoji = "\u{1F52B}",
        theatre = "infantry",
        hp = 70,
        maxHp = 70,
        atk = 26,
        def = 15,
        move = 2,
        range = 2,
        cost = 22,
        deployable = true,
        ability = "Suppressive Fire",
        abilityDesc = "Ranged attack at range 2. Target skips next move.",
    },
    mole = {
        name = "Mole Jonk",
        icon = "hole",
        emoji = "\u{1F573}",
        theatre = "infantry",
        hp = 50,
        maxHp = 50,
        atk = 20,
        def = 8,
        move = 2,
        range = 2,
        cost = 18,
        deployable = true,
        ability = "Underground Spit",
        abilityDesc = "Attacks with no counter-attack. Plants a trap on adjacent tile.",
    },
    commander = {
        name = "Commander Jonk",
        icon = "star",
        emoji = "\u{2B50}",
        theatre = "infantry",
        hp = 65,
        maxHp = 65,
        atk = 15,
        def = 18,
        move = 2,
        range = 1,
        cost = 25,
        deployable = true,
        ability = "Rally",
        abilityDesc = "Boosts ATK of all friendly infantry within 2 tiles by +8 for this turn.",
    },
    lawyer = {
        name = "Lawyer Jonk",
        icon = "scales",
        emoji = "\u{2696}",
        theatre = "infantry",
        hp = 45,
        maxHp = 45,
        atk = 0,
        def = 0,
        move = 2,
        range = 3,
        cost = 20,
        deployable = true,
        ability = "Sue",
        abilityDesc = "Sues opponent for up to 25% of their current gold.",
    },
    lubatron = {
        name = "Lubatron",
        icon = "water",
        emoji = "\u{1F30A}",
        theatre = "infantry",
        hp = 55,
        maxHp = 55,
        atk = 10,
        def = 10,
        move = 2,
        range = 2,
        cost = 18,
        deployable = true,
        ability = "Grease Spill",
        abilityDesc = "Enemy troops cost +1 move for 2 turns.",
    },
    railgun = {
        name = "Railgun Jonk",
        icon = "target",
        emoji = "\u{1F3AF}",
        theatre = "infantry",
        hp = 45,
        maxHp = 45,
        atk = 55,
        def = 5,
        move = 1,
        range = 5,
        cost = 45,
        deployable = true,
        locked = 100, -- games played to unlock
        ability = "Bean Shot",
        abilityDesc = "OP ranged attack at range 5.",
    },
    mole_daddy = {
        name = "Mole Daddy",
        icon = "microbe",
        emoji = "\u{1F9A0}",
        theatre = "infantry",
        hp = 80,
        maxHp = 80,
        atk = 35,
        def = 15,
        move = 1,
        range = 1,
        cost = 50,
        deployable = true,
        locked = 500, -- games played to unlock
        ability = "Drill Strike",
        abilityDesc = "Gives all Mole Jonks drills for devastating tunnel attacks.",
    },
    river_rat = {
        name = "River Rat Jonk",
        icon = "speedboat",
        emoji = "\u{1F6A4}",
        theatre = "naval",
        hp = 40,
        maxHp = 40,
        atk = 12,
        def = 5,
        move = 4,
        range = 2,
        cost = 16,
        deployable = true,
        ability = "Turbo Boost",
        abilityDesc = "Extremely fast boat -- moves 4 tiles.",
    },
    transport = {
        name = "Transport Jonk",
        icon = "ship",
        emoji = "\u{1F6A2}",
        theatre = "naval",
        hp = 90,
        maxHp = 90,
        atk = 5,
        def = 20,
        move = 2,
        range = 0,
        cost = 18,
        deployable = true,
        ability = "Ferry",
        abilityDesc = "Carries up to 2 infantry units across the river.",
    },
    borei = {
        name = "Borei Jonk",
        icon = "moon",
        emoji = "\u{1F311}",
        theatre = "naval",
        hp = 70,
        maxHp = 70,
        atk = 30,
        def = 18,
        move = 2,
        range = 4,
        cost = 35,
        deployable = true,
        ability = "Missile Salvo",
        abilityDesc = "Russian submarine with 8 multi-role lock-on missiles.",
    },
    war_pirate = {
        name = "War Pirate",
        icon = "skull",
        emoji = "\u{2620}",
        theatre = "naval",
        hp = 55,
        maxHp = 55,
        atk = 18,
        def = 12,
        move = 3,
        range = 1,
        cost = 24,
        deployable = true,
        ability = "Hijack",
        abilityDesc = "Boards enemy naval vessel and controls it for 1 turn.",
    },
    zumwalt = {
        name = "Zumwalt Jonk",
        icon = "anchor",
        emoji = "\u{2693}",
        theatre = "naval",
        hp = 120,
        maxHp = 120,
        atk = 50,
        def = 25,
        move = 2,
        range = 5,
        cost = 60,
        deployable = true,
        locked = "mission", -- special mission unlock
        ability = "Full Salvo",
        abilityDesc = "SUPER OP. 3 instant-destroy ground missiles + 3 air missiles.",
    },
}

-- Ordered lists for UI display
UnitDefs.InfantryOrder = {
    "king", "guard", "spear", "marine", "mole",
    "commander", "lawyer", "lubatron", "railgun", "mole_daddy",
}

UnitDefs.NavalOrder = {
    "river_rat", "transport", "borei", "war_pirate", "zumwalt",
}

-- Get a copy of unit stats for spawning
function UnitDefs.createUnit(unitType, owner, row, col)
    local def = UnitDefs.Types[unitType]
    if not def then return nil end
    return {
        type = unitType,
        name = def.name,
        hp = def.maxHp,
        maxHp = def.maxHp,
        owner = owner,
        row = row,
        col = col,
        moved = false,
        attacked = false,
        usedAbility = false,
        dead = false,
    }
end

return UnitDefs
